import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const RobotoFont = Roboto({
   weight: "400",
   display: 'swap',
   subsets: ["latin"]
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={RobotoFont.className}>
            <Header />
            <main className="pt-16">
               {children}
            </main>
            <Footer />
         </body>
      </html>
   );
}
